- docs/concepts/layout/en.md
- docs/concepts/layout/pt.md
- docs/concepts/section/pt.md
- docs/concepts/site/pt.md
- docs/migration-guides/v1.x/en.md
- docs/migration-guides/v1.x/pt.md
- docs/recipes/images/pt.md
- docs/toc.ts
- docs/tutorials/creating-a-layout/en.md
- docs/tutorials/creating-a-layout/pt.md
- import_map.json
- schemas.gen.json
The docs were outdated from www
> Migrate docs from www

- components/utils/markdown.ts
- deno.json
- import_map.json
- main.ts
- routes/_app.tsx
Upgrade deps, remove hard-coded analytics and  and use the new analytics section from deco-sites/std
> upgrade deps and use std

- docs/toc.ts
test path: /docs/en/performance/tips/svg-sprites
> fix: render nested page

- docs/toc.ts
- docs/treinamento-comercial/agencias-parceiras/pt.md
- docs/treinamento-comercial/nichos-de-clientes/pt.md
- docs/treinamento-comercial/objecoes/pt.md
- docs/treinamento-comercial/proximos-passos/pt.md
- docs/treinamento-comercial/seu-primeiro-case/pt.md
Agências Parceiras
Nichos de Clientes
Objeções
Seu Primeiro Case
Próximos passos
> Treinamento comercial - Mais

- components/utils/Blog.ts
- live.gen.ts
- loaders/blogPostMarkdownLoader.ts
Markdown loader for posts global
> feat: add blog content markdown loader

- components/blog/FeaturedPost.tsx
- components/blog/PostCard.tsx
- components/ui/Carousel.tsx
- components/utils/Blog.ts
- sdk/utils.ts
- sections/BlogPostHeader.tsx
- sections/BlogPostList.tsx
Allow blog posts to be located under both `/en` and `/pt` (or whatever you want)
> feat: allow multiple blog locales

- components/seo/BlogMetatags.tsx
- components/seo/BlogPostSEO.tsx
- components/utils/Blog.ts
- live.gen.ts
- loaders/blogPostDetailsLoader.ts
- sections/BlogPostSEO.tsx
Add blog post page seo section
> feat: add blog post page seo section

- components/seo/BlogPostSEO.tsx
fix: correct post properties accessors
> fix: correct post properties accessors

- docs/hub/create-new/en.md
- docs/hub/create-new/pt.md
- docs/toc.ts
https://deco-sites-starting-3d3x6e96m7bm.deno.dev/docs/en/hub/create-new
https://deco-sites-starting-3d3x6e96m7bm.deno.dev/docs/pt/hub/create-new
> Create a new integration

- components/decohelp/pages/ui/Content/Content.tsx
temporary solution, breadcrumb component hook was blocking the documentation view
> commenting BreadCrumb component

- docs/getting-started/creating-a-new-page/pt.md
- docs/getting-started/creating-a-site/pt.md
- docs/getting-started/installing-an-app/pt.md
- docs/getting-started/updating-seo/pt.md
- docs/getting-started/variants/pt.md
- manifest.gen.ts
- Fixing links, texts, removing old images, and correcting translation for 'Getting Started'.
> docs: fix information

- docs/concepts/action/en.md
- docs/concepts/loader/en.md
- docs/concepts/page/en.md
- docs/concepts/section/en.md
- docs/getting-started/creating-a-new-page/en.md
- docs/getting-started/custom-domains/en.md
- docs/getting-started/custom-domains/pt.md
- docs/getting-started/installing-an-app/en.md
- docs/getting-started/installing-an-app/pt.md
- docs/getting-started/proxy-redirects/en.md
- docs/getting-started/proxy-redirects/pt.md
- docs/getting-started/releases-revisions/en.md
- docs/getting-started/releases-revisions/pt.md
- docs/getting-started/updating-seo/en.md
- docs/getting-started/variants/en.md
This pull request changes consist of:
* Updating outdated links
* Fixing incorrect links
* Small spelling/grammar corrections
* Fixing ordered lists indentation
[Loom preview of the changes](https://www.loom.com/share/d90ed71d6c194ce789532a1801ce2241?sid=93fd57a6-03bd-460b-a87c-ec6be048f18e)
> Docs update: Getting Started and Concepts

- docs/developing/editable-sections/en.md
- docs/developing/editable-sections/pt.md
- docs/developing/fetching-data/en.md
- docs/developing/fetching-data/pt.md
- docs/developing/hello-world/en.md
- docs/developing/hello-world/pt.md
- docs/developing/islands/en.md
- docs/developing/islands/pt.md
- docs/developing/setup/en.md
- docs/developing/setup/pt.md
- docs/toc.ts
The alterations done in this PR consists of:
* Adding clarifications to the tutorial so it can be simpler to follow.
* Updating information.
* Typo corrections.
* Code correction.
> Update docs - Developing: Typo correction, clarifications and updated info

- sections/Live Projects/ProjectsGrid.tsx
- adding possibility to define the value of the general name in the tab
> feat: add nomeDaCategoriaGeral in ProjectsGrid

- components/camp/Button/Button.tsx
- components/camp/Hero/Hero.tsx
- fresh.gen.ts
- routes/_middleware.ts
insert style='color-scheme: dark' into html doc when route is /decocamp
> fix decocamp darkmode

- components/ui/whatsapp.tsx
- manifest.gen.ts
> whatsapp icon enlargement

- sections/Case/ArticleHeader.tsx
- sections/Case/ArticleYoutubeVideo.tsx
> Youtube Embed Video proper functioning:
> Logo ArticleHeader Props row display:
> Feat: Case Layout Landing Hotfix

- components/producthunt/Roadmap.tsx
- components/ui/Markdown.tsx
- islands/NRF/Header.tsx
- sections/Hub/Integrations.tsx
- sections/Hub/SectionTitle.tsx
- sections/Live Projects/Hero.tsx
- sections/Live Projects/LiveProjects.tsx
- sections/Live Projects/ProjectsGrid.tsx
Docs Requested fixes: https://docs.google.com/document/d/1eKEWaTjd_w2lstw042jNrbAoVPG9qYK-wpxnMD2AhOw/edit
> Requested Layout Fixes Deco 2.0 - Home, Hub and Resources

- overrides/gfm.mod.ts
- routes/gfm.css.ts
- sections/MarkdownContent.tsx
- sections/Page.tsx
- static/docs/js/copy-snippets.js
> docs(fix): Prism syntax highlighting + add copy button to code snippets + content styles

- docs/developing/creating-an-app/en.md
- docs/developing/creating-an-app/pt.md
Something minor I realized yesterday ;p
> docs(developing): fix wrong startup script command

- docs/api-reference/invoke/en.md
- docs/api-reference/invoke/pt.md
- docs/toc.ts
This PR Depends on https://github.com/deco-cx/deco/pull/733 merging first to make sense.
> New docs: Invoke
